### ISSUE TITLE
Catching exceptions

### ISSUE THREAD

**Issue by kezern** [cartalyst/stripe-laravel#31] opened 2017-09-19 17:00 UTC
I'm developing an application using laravel and Crudbooster.
I want to catch card exceptions.
I have this code.
			try{	        
		        $stripe = Stripe::make($key);
		        
		       	$token = $stripe->tokens()->create([
		            'card' => [
		                'number'    => $cobro->tarjeta,
		                'exp_month' => $card_date[0],
		                'cvc'       => $cobro->cvv,
		                'exp_year'  => '20'.$card_date[1],
		            ],
		        ]);

		        //Log::info('token: '.print_r($token, true));

		       	$charge = $stripe->accountId('acct_XXXXXXXXXX')->charges()->create([
		            'currency' => 'EUR',
		            'amount'   => $cobro->importe,
		            'source' => $token['id'],
		            'description' => $cobro->descripcion,
		            //'source' => 'tok_es',
		            "application_fee" => $application_fee,
		        ]);
	       		
	       	}catch(Cartalyst\Stripe\Exception\CardErrorException $e){
	       		Log::error("Se ha procudido una excepcion ".$e->getMessage());
	       	}

But exception is not catched and Whoops error of laravel is shown

**Comment by brunogaspar** [comment] 2017-09-19 17:07
Duplicate of #17

**Closed as completed by brunogaspar** 2017-09-19 17:07 UTC

**Comment by kezern** [comment] 2017-09-19 17:18
Thanks! Sorry I didn't find that
